name: Test Policies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://openpolicyagent/opa
        with:
          args: "test --ignore=*.yaml --ignore=*.json -v compliance"
          
          
#   opa:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - uses: docker://openpolicyagent/opa

#     - name: Set up Python
#       uses: actions/setup-python@v2
    
#     - name: Print OPA version
#       run: opa version
    
# #     - name: Download OPA Binary
# #       run: |
# #         curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
# #         chmod 755 ./opa
    
#     - name: Run Pre-Commit hooks
#       uses: pre-commit/action@v2.0.3

