name: Test Coverage

on:
  push:
    branches: [main]
    
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download OPA Binary
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          ./opa -h
      
      - name: OPA test coverage
        run: |
          RESULT=$(./opa test -v -c compliance)
          echo "RESULT<<EOF" >> $GITHUB_ENV
          echo "$RESULT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - run: |  
          echo "COVERAGE=$(fromJson(env.RESULT).coverage)" >> $GITHUB_ENV
          
      - name: Set coverage badge color
        run: |
          if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
            echo "COLOR=red" >> $GITHUB_ENV
          elif (( $(echo "$COVERAGE > 80" | bc -l) )); then
            echo "COLOR=green" >> $GITHUB_ENV
          else
            echo "COLOR=orange" >> $GITHUB_ENV
          fi
        
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a7160df46e48dff45b24096de9302d38
          filename: csp-security-policies_coverage.json
          label: coverage
          message: ${{ env.COLOR }}
          namedLogo: Elastic
          color: green
          logoColor: lightblue
